### ISSUE TITLE
"mco package apt_checkupdates" gives no package information output 

### ISSUE THREAD

**Issue by KoenDierckx** [choria-plugins/package-agent#8]
Ubuntu 16.04 lts
apt 1.2.27 (amd64)
puppet 4.10.12
choria 0.5.0
mco 2.10.6

mco package apt_checkupdates 
Do you really want to operate on packages unfiltered? (y/n): y
 * [ ============================================================> ] 17 / 17
Finished processing 17 / 17 hosts in 1548.26 ms

mco package apt_checkupdates -v
Do you really want to operate on packages unfiltered? (y/n): y
Discovering hosts using the mc method for 2 second(s) .... 17
 * [ ============================================================> ] 17 / 17
          puppet.local:
                test.local:
                            ....
---- apt_checkupdates Package results ----
           Nodes: 17 / 17
     Pass / Fail: 17 / 0
      Start Time: 2018-08-06 09:20:05 +0200
  Discovery Time: 2030.01ms
      Agent Time: 2934.38ms
      Total Time: 4964.39ms

I would expect the hosts to show the packages that have updates, and the version information for those packages.

What can I do to help find the cause of the problem ?

**Comment by ripienaar** [comment]
That appears to be fine and does parse with the regex, maybe edit here:

https://github.com/choria-plugins/package-agent/blob/473255bf70168ad06444c0621d9fdf216195239a/util/package/packagehelpers.rb#L202

add `Log.warn(result.inspect)`

then restart a node and show me what you get in the log for the node

**Comment by KoenDierckx** [comment]
==> /var/log/puppetlabs/mcollective-audit.log <==
{"timestamp":"2018-08-08T05:34:37.553136+0000","request_id":"64e19cb1bcb353b09fd5c45e902f7793","request_time":1533706477,"caller":"choria=xxx.mcollective","sender":"puppet.local","agent":"package","action":"apt_checkupdates","data":{"package":null,"process_results":true}}

==> /var/log/puppetlabs/mcollective.log <==
W, [2018-08-08T07:34:38.669899 #21937]  WARN -- : packagehelpers.rb:201:in `apt_checkupdates' {:exitcode=>0, :output=>"Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following packages will be upgraded:\n  libglib2.0-0 libglib2.0-data\n2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nInst libglib2.0-0 [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nInst libglib2.0-data [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\nConf libglib2.0-0 (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nConf libglib2.0-data (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\n", :outdated_packages=>[], :package_manager=>"apt"}

**Comment by KoenDierckx** [comment]
I've also logged the result, just before it gets returned, the parsing seems fine, as outdated_packages is filled in correctly

W, [2018-08-08T07:38:44.651076 #21937]  WARN -- : packagehelpers.rb:214:in `apt_checkupdates' {:exitcode=>0, :output=>"Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following packages will be upgraded:\n  libglib2.0-0 libglib2.0-data\n2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nInst libglib2.0-0 [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nInst libglib2.0-data [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\nConf libglib2.0-0 (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nConf libglib2.0-data (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\n", :outdated_packages=>[{:package=>"libglib2.0-0", :version=>"2.48.2-0ubuntu4", :repo=>"Ubuntu:16.04/xenial-updates [amd64]"}, {:package=>"libglib2.0-data", :version=>"2.48.2-0ubuntu4", :repo=>"Ubuntu:16.04/xenial-updates [all]"}], :package_manager=>"apt"}

**Comment by ripienaar** [comment]
Ok so then with this filled in what happens on the cli? This seems all fine. Add -v and show the mco output at the time the log shows it’s cirrectly filled in please

**Comment by KoenDierckx** [comment]
Completely the same as the first post I made. 

"mco package count" works completely fine, so there is no issue with communication between the hosts

**Comment by ripienaar** [comment]
Is this running against choria server or mcollectived still?

Pls show `mco rpc package apt_checkupdates -v`

**Comment by KoenDierckx** [comment]
Aha, I missed the rpc part

$ mco rpc package apt_checkupdates -v
Discovering hosts using the mc method for 2 second(s) .... 17
 * [ ============================================================> ] 17 / 17
puppet.local                  : OK
    {:output=>      "Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following packages will be upgraded:\n  foreman foreman-compute foreman-debug foreman-ec2 foreman-postgresql\n  foreman-proxy foreman-vmware x11-common\n8 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nInst x11-common [1:7.7+13ubuntu3] (1:7.7+13ubuntu3.1 Ubuntu:16.04/xenial-updates [all])\nInst foreman-vmware [1.16.1-1] (1.16.2-1 TheForeman:xenial [all]) []\nInst foreman-postgresql [1.16.1-1] (1.16.2-1 TheForeman:xenial [all]) []\nInst foreman-ec2 [1.16.1-1] (1.16.2-1 TheForeman:xenial [all]) []\nInst foreman-compute [1.16.1-1] (1.16.2-1 TheForeman:xenial [all]) []\nInst foreman [1.16.1-1] (1.16.2-1 TheForeman:xenial [amd64])\nInst foreman-debug [1.16.1-1] (1.16.2-1 TheForeman:xenial [all])\nInst foreman-proxy [1.16.1-1] (1.16.2-1 TheForeman:xenial [all])\nConf x11-common (1:7.7+13ubuntu3.1 Ubuntu:16.04/xenial-updates [all])\nConf foreman (1.16.2-1 TheForeman:xenial [amd64])\nConf foreman-vmware (1.16.2-1 TheForeman:xenial [all])\nConf foreman-postgresql (1.16.2-1 TheForeman:xenial [all])\nConf foreman-ec2 (1.16.2-1 TheForeman:xenial [all])\nConf foreman-compute (1.16.2-1 TheForeman:xenial [all])\nConf foreman-debug (1.16.2-1 TheForeman:xenial [all])\nConf foreman-proxy (1.16.2-1 TheForeman:xenial [all])\n",     :outdated_packages=>      [{:package=>"x11-common",        :version=>"1:7.7+13ubuntu3.1",        :repo=>"Ubuntu:16.04/xenial-updates [all]"},       {:package=>"foreman-vmware",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"},       {:package=>"foreman-postgresql",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"},       {:package=>"foreman-ec2",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"},       {:package=>"foreman-compute",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"},       {:package=>"foreman",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [amd64]"},       {:package=>"foreman-debug",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"},       {:package=>"foreman-proxy",        :version=>"1.16.2-1",        :repo=>"TheForeman:xenial [all]"}],     :exitcode=>0,     :package_manager=>"apt"}

test.local                : OK
    {:output=>      "Reading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\nThe following packages will be upgraded:\n  libglib2.0-0 libglib2.0-data\n2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\nInst libglib2.0-0 [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nInst libglib2.0-data [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\nConf libglib2.0-0 (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])\nConf libglib2.0-data (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])\n",     :outdated_packages=>      [{:package=>"libglib2.0-0",        :version=>"2.48.2-0ubuntu4",        :repo=>"Ubuntu:16.04/xenial-updates [amd64]"},       {:package=>"libglib2.0-data",        :version=>"2.48.2-0ubuntu4",        :repo=>"Ubuntu:16.04/xenial-updates [all]"}],     :exitcode=>0,     :package_manager=>"apt"}

...

---- package#apt_checkupdates call stats ----
           Nodes: 17 / 17
     Pass / Fail: 17 / 0
      Start Time: 2018-08-08 07:51:48 +0200
  Discovery Time: 2002.83ms
      Agent Time: 1589.45ms
      Total Time: 3592.27ms

**Comment by KoenDierckx** [comment]
>>Is this running against choria server or mcollectived still?
I assume mcollectived (but I might be wrong)
we are using puppet 4, and the choria docs stated that it requires puppet 5

**Comment by ripienaar** [comment]
Ok. So `mco package ....` does say it should have worked but honestly I don’t think it should - this data isn’t exactly human consumable it’s too much and too structured. 

The `mco package` is supposed to be a human friendly interface to the data produced by the agent but it makes no effort to render this data correctly. The `mco rpc package` just dumps it and still not human friendly. The intention with the check updates actions is that they should be used to build other automations - ie. they are consumed by programs not people. 

I am inclined to just remove the stated support for it from `mco package`

**Comment by KoenDierckx** [comment]
Without the -v, the rpc version is more user friendly

`monitor01.sas.vito.local
           Exit Code: 0
   Outdated Packages: [{:package=>"libglib2.0-0",
                        :version=>"2.48.2-0ubuntu4",
                        :repo=>"Ubuntu:16.04/xenial-updates [amd64]"},
                       {:package=>"libglib2.0-data",
                        :version=>"2.48.2-0ubuntu4",
                        :repo=>"Ubuntu:16.04/xenial-updates [all]"}]
              Output: Reading package lists...
                      Building dependency tree...
                      Reading state information...
                      Calculating upgrade...
                      The following packages will be upgraded:
                        libglib2.0-0 libglib2.0-data
                      2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
                      Inst libglib2.0-0 [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])
                      Inst libglib2.0-data [2.48.2-0ubuntu3] (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])
                      Conf libglib2.0-0 (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [amd64])
                      Conf libglib2.0-data (2.48.2-0ubuntu4 Ubuntu:16.04/xenial-updates [all])
     package_manager: apt
`

**Comment by KoenDierckx** [comment]
But then nicely indented (lost in comment box)

**Comment by ripienaar** [comment]
Yeah generally -v shouldn’t ever be needed. Handy to see the raw data un rendered

**Comment by KoenDierckx** [comment]
So if I understand correctly, the choria package agent produces output the mcollective mco package command doesn't now how to render ?

**Comment by ripienaar** [comment]
Yes appears so. So I will remove it since I don’t think it’s usable there.  Will add a comment that people can use mco rpc to get at it. Or maybe just print the data like rpc does for those actions. 

The `mco package` code is a bit shit tbh :)

**Comment by KoenDierckx** [comment]
And your code is a fork of the "official" one?
https://github.com/puppetlabs/mcollective-package-agent

Because the packagehelpers.rb seems to be identical. 
So it should work then, one would assume

**Comment by KoenDierckx** [comment]
The problem is here:
/opt/puppetlabs/mcollective/plugins/mcollective/application/package.rb
This has no support for apt_checkupdates as far as I can see

**Comment by ripienaar** [comment]
Yup. That’s what been saying. But —help will show it does.

**Comment by KoenDierckx** [comment]
I've created a very quick PR #9

**Comment by KoenDierckx** [comment]
$ mco package checkupdates
Do you really want to operate on packages unfiltered? (y/n): y

 * [ ============================================================> ] 17 / 17

        test.local: libglib2.0-0 libglib2.0-data
          puppet.local: x11-common foreman-vmware foreman-postgresql foreman-ec2 foreman-compute foreman foreman-debug foreman-proxy
...
Finished processing 17 / 17 hosts in 2260.70 ms

**Comment by ripienaar** [comment]
sorry this one kind of fell off the radar, will release soon
